// 羊了个羊 · 类型库

const cardTypeLibrary = [
  { typeId: "type-1", imageFile: "type-1.png" },
  { typeId: "type-2", imageFile: "type-2.png" },
  { typeId: "type-3", imageFile: "type-3.png" },
  { typeId: "type-4", imageFile: "type-4.png" },
  { typeId: "type-5", imageFile: "type-5.png" },
  { typeId: "type-6", imageFile: "type-6.png" },
  { typeId: "type-7", imageFile: "type-7.png" },
  { typeId: "type-8", imageFile: "type-8.png" },
  { typeId: "type-9", imageFile: "type-9.png" },
  { typeId: "type-10", imageFile: "type-10.png" },
  { typeId: "type-11", imageFile: "type-11.png" },
  { typeId: "type-12", imageFile: "type-12.png" },
  { typeId: "type-13", imageFile: "type-13.png" },
  { typeId: "type-14", imageFile: "type-14.png" },
  { typeId: "type-15", imageFile: "type-15.png" },
  { typeId: "type-16", imageFile: "type-16.png" },
  { typeId: "type-17", imageFile: "type-17.png" },
  { typeId: "type-18", imageFile: "type-18.png" },
  { typeId: "type-19", imageFile: "type-19.png" },
  { typeId: "type-20", imageFile: "type-20.png" },
  { typeId: "type-21", imageFile: "type-21.png" },
  { typeId: "type-22", imageFile: "type-22.png" },
  //   { typeId: "type-23", imageFile: "type-23.png" },
  //   { typeId: "type-24", imageFile: "type-24.png" },
  //   { typeId: "type-25", imageFile: "type-25.png" },
];

// const cardTypeLibrary = [
//   { typeId: "type-1", displayChar: "🐑" },
//   { typeId: "type-2", displayChar: "🍎" },
//   { typeId: "type-3", displayChar: "🌲" },
//   { typeId: "type-4", displayChar: "🥕" },
//   { typeId: "type-5", displayChar: "🐔" },
//   { typeId: "type-6", displayChar: "🐄" },
//   { typeId: "type-7", displayChar: "🌽" },
//   { typeId: "type-8", displayChar: "🍅" },
//   { typeId: "type-9", displayChar: "🐖" },
//   { typeId: "type-10", displayChar: "🐟" },
//   { typeId: "type-11", displayChar: "🍞" },
//   { typeId: "type-12", displayChar: "🧀" },
//   { typeId: "type-13", displayChar: "🥛" },
//   { typeId: "type-14", displayChar: "🍇" },
//   { typeId: "type-15", displayChar: "🍓" },
//   // 以后可以继续加，到 type-100
// ];
